// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuOzIeG_PJKAv2m5RONcVdpk7DUdsb4W4',
    appId: '1:487719915215:web:7e82ce67ba92f0e57db1ba',
    messagingSenderId: '487719915215',
    projectId: 'mynotes-c3070',
    authDomain: 'mynotes-c3070.firebaseapp.com',
    storageBucket: 'mynotes-c3070.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7sloLW4gRydVqiox88EuLFLgNbk4tHII',
    appId: '1:487719915215:android:36e34d3e11de64a77db1ba',
    messagingSenderId: '487719915215',
    projectId: 'mynotes-c3070',
    storageBucket: 'mynotes-c3070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQlCalx0RPrPfuD4v7bW3onpIDzZ1f5hc',
    appId: '1:487719915215:ios:5dd7caf0c7c947e97db1ba',
    messagingSenderId: '487719915215',
    projectId: 'mynotes-c3070',
    storageBucket: 'mynotes-c3070.appspot.com',
    iosBundleId: 'de.vdn24.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQlCalx0RPrPfuD4v7bW3onpIDzZ1f5hc',
    appId: '1:487719915215:ios:67619e7fa92558ed7db1ba',
    messagingSenderId: '487719915215',
    projectId: 'mynotes-c3070',
    storageBucket: 'mynotes-c3070.appspot.com',
    iosBundleId: 'de.vdn24.mynotes.RunnerTests',
  );
}
